services:
  - type: web
    name: office-energy-monitor-backend
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: python manage.py migrate --noinput && python manage.py seed_devices && gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: office-energy-monitor-y6jt.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://office-energy-monitor.netlify.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://office-energy-monitor.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: office-energy-monitor-db
          property: connectionString

  - type: worker
    name: office-energy-monitor-simulator
    runtime: python
    rootDir: backend
    buildCommand: ./build.sh
    startCommand: python manage.py migrate --noinput && python manage.py seed_devices && python manage.py simulate_devices
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: office-energy-monitor-y6jt.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://office-energy-monitor.netlify.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://office-energy-monitor.netlify.app
      - key: DATABASE_URL
        fromDatabase:
          name: office-energy-monitor-db
          property: connectionString

  - type: worker
    name: office-energy-monitor-discord-bot
    runtime: python
    rootDir: bot
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: API_BASE_URL
        value: https://office-energy-monitor-y6jt.onrender.com/api
      - key: ALERT_CHANNEL_ID
        sync: false

databases:
  - name: office-energy-monitor-db
    databaseName: office_energy_monitor
    user: office_energy_monitor
